name: Scala Library

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  publish:
    runs-on: ubuntu-latest

    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/$default-branch' }}

    needs: [test, lint, dependencyCheck]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/*') }}
      - name: Publish
        run: sbt ';test;set credentials += Credentials("Artifactory Realm", "artifactory.agrian.com", "teamcity", "${{ secrets.ARTIFACTORYKEY }}");+publish'

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Ivy and SBT artifacts
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/*') }}
      - name: Run tests
        run: sbt ';set coverageFailOnMinimum := true;clean;set coverageEnabled := true;coverage;test;coverageReport;coverageAggregate'
      - name: Publish Test Report
        uses: agrian-inc/action-junit-report@main
        if: always()
        with:
          report_paths: "**/test-reports/TEST-*.xml"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Save coverage
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: coverage
          path: target/scala-2.12/scoverage-report/
          retention-days: 1

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/*') }}
      - name: Scalafmt
        run: sbt scalastyle scalafmtSbtCheck scalafmtCheck test:scalafmtCheck

  dependencyCheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/*') }}
      - name: Dependency Check
        run: sbt dependencyCheck
